from __future__ import annotations

import asyncio
import secrets
import sys
from pathlib import Path

from geminichat.bootstrap import bootstrap_from_session
from geminichat.exceptions import GeminiChatError

_HELP = """
How to get your Google session for Gemini:

  1. Open https://aistudio.google.com and log in with your Google account.
  2. DevTools (F12) → Application → Cookies → https://aistudio.google.com
  3. Copy the full document.cookie string.
  4. Paste it below (or pass --cookie).

This stores a browser *session* (including SAPISID). It is NOT an API key.
A real Gemini API key must be created separately at
https://aistudio.google.com/apikey — it cannot be extracted from cookies.

Your session gives this proxy access to the Gemini models your account is
allowed to use, exposed as an OpenAI-compatible API on your local machine.
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _generate_api_key() -> str:
    return f"sk-geminichat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m geminichat setup",
        f"GEMINICHAT_API_KEY={values['GEMINICHAT_API_KEY']}",
        f"GEMINICHAT_HOST={values.get('GEMINICHAT_HOST', '127.0.0.1')}",
        f"GEMINICHAT_PORT={values.get('GEMINICHAT_PORT', '1997')}",
        f"GEMINICHAT_ACCOUNT={values.get('GEMINICHAT_ACCOUNT', 'gemini_account.json')}",
        f"GEMINICHAT_DEFAULT_MODEL={values.get('GEMINICHAT_DEFAULT_MODEL', 'gemini-2.5-flash')}",
    ]
    cookie = values.get("GEMINICHAT_COOKIE", "").strip()
    if cookie:
        lines.append(f"GEMINICHAT_COOKIE={cookie}")
    sapisid = values.get("GEMINICHAT_SAPISID", "").strip()
    if sapisid:
        lines.append(f"GEMINICHAT_SAPISID={sapisid}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    account_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    _print()
    _print("Setup complete.")
    _print(f"  Account file : {account_path}")
    if env_written:
        _print(f"  Environment  : {env_path}")
    else:
        _print("  Environment  : (skipped)")
    _print()
    _print("Start the server:")
    _print("  python -m geminichat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print()
    _print(f"  Base URL: http://{host}:{port}/v1")
    _print()
    _print("NOTE: this uses a browser session, not a real Gemini API key. If")
    _print("streaming fails, review the 'REVIEW' markers in geminichat/client.py.")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    cookie: str | None = None,
    sapisid: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = (env_path or Path(".env")).expanduser()
    account_path = (account_path or Path("gemini_account.json")).expanduser()
    write_env = True

    _print("GeminiChat setup")
    _print("================")
    _print()
    _print("This wizard will:")
    _print("  • capture your Google session (not an API key)")
    _print("  • save gemini_account.json")
    _print("  • create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    if cookie or sapisid:
        final_cookie = cookie or ""
        final_sapisid = sapisid or ""
    else:
        _print(_HELP)
        _print()
        _print("Paste your aistudio.google.com cookie string, then press Enter:")
        final_cookie = input("> ").strip()
        final_sapisid = sapisid or ""

    _print()
    _print("Saving Gemini session...")
    try:
        account = await bootstrap_from_session(
            final_cookie,
            sapisid=final_sapisid,
            account_path=str(account_path),
        )
    except GeminiChatError as exc:
        _print(f"  Error: {exc}", file=sys.stderr)
        return 1

    _print(f"  Email: {account.user_email or '(unknown)'}")

    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("GEMINICHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("GEMINICHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("GEMINICHAT_PORT") or "1997"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)

    if write_env:
        env_updates = {
            "GEMINICHAT_API_KEY": resolved_api_key,
            "GEMINICHAT_HOST": resolved_host,
            "GEMINICHAT_PORT": resolved_port,
            "GEMINICHAT_ACCOUNT": account_path.name,
            "GEMINICHAT_COOKIE": final_cookie,
        }
        if final_sapisid:
            env_updates["GEMINICHAT_SAPISID"] = final_sapisid
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        account_path=account_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0
