from __future__ import annotations

import asyncio
import secrets
import sys
from pathlib import Path

from boltchat.account import build_bolt_account
from boltchat.bootstrap import bootstrap_from_session
from boltchat.exceptions import BoltChatError

_HELP = """
How to get your Bolt.new session:

  1. Open https://bolt.new in your browser and log in.
  2. Open DevTools (F12) → Application → Cookies → https://bolt.new
  3. Copy the full document.cookie string.
  4. Paste it below (or pass --cookie).

This stores a browser *session*, not an "API key". Bolt.new routes to its AI
models server-side; your session determines which models/quotas you can reach.
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _generate_api_key() -> str:
    return f"sk-boltchat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m boltchat setup",
        f"BOLTCHAT_API_KEY={values['BOLTCHAT_API_KEY']}",
        f"BOLTCHAT_HOST={values.get('BOLTCHAT_HOST', '127.0.0.1')}",
        f"BOLTCHAT_PORT={values.get('BOLTCHAT_PORT', '1996')}",
        f"BOLTCHAT_ACCOUNT={values.get('BOLTCHAT_ACCOUNT', 'bolt_account.json')}",
        f"BOLTCHAT_DEFAULT_MODEL={values.get('BOLTCHAT_DEFAULT_MODEL', 'bolt-agent')}",
    ]
    cookie = values.get("BOLTCHAT_COOKIE", "").strip()
    if cookie:
        lines.append(f"BOLTCHAT_COOKIE={cookie}")
    token = values.get("BOLTCHAT_SESSION_TOKEN", "").strip()
    if token:
        lines.append(f"BOLTCHAT_SESSION_TOKEN={token}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    account_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    _print()
    _print("Setup complete.")
    _print(f"  Account file : {account_path}")
    if env_written:
        _print(f"  Environment  : {env_path}")
    else:
        _print("  Environment  : (skipped)")
    _print()
    _print("Start the server:")
    _print("  python -m boltchat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print()
    _print(f"  Base URL: http://{host}:{port}/v1")
    _print()
    _print("NOTE: Bolt.new's AI transport is proprietary. If streaming returns no")
    _print("text, review the 'REVIEW' markers in boltchat/client.py against the")
    _print("live site (DevTools -> Network -> WS).")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    cookie: str | None = None,
    session_token: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = (env_path or Path(".env")).expanduser()
    account_path = (account_path or Path("bolt_account.json")).expanduser()
    write_env = True

    _print("BoltChat setup")
    _print("==============")
    _print()
    _print("This wizard will:")
    _print("  • capture your Bolt.new browser session")
    _print("  • save bolt_account.json")
    _print("  • create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    if cookie or session_token:
        final_cookie = cookie or ""
        final_token = session_token or ""
    else:
        _print(_HELP)
        _print()
        _print("Paste your Bolt.new cookie string, then press Enter:")
        final_cookie = input("> ").strip()
        final_token = session_token or ""

    _print()
    _print("Saving Bolt session...")
    try:
        account = await bootstrap_from_session(
            final_cookie,
            session_token=final_token,
            account_path=str(account_path),
        )
    except BoltChatError as exc:
        _print(f"  Error: {exc}", file=sys.stderr)
        return 1

    _print(f"  User: {account.user_name or account.user_id or '(unknown)'}")

    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("BOLTCHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("BOLTCHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("BOLTCHAT_PORT") or "1996"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)

    if write_env:
        env_updates = {
            "BOLTCHAT_API_KEY": resolved_api_key,
            "BOLTCHAT_HOST": resolved_host,
            "BOLTCHAT_PORT": resolved_port,
            "BOLTCHAT_ACCOUNT": account_path.name,
            "BOLTCHAT_COOKIE": final_cookie,
        }
        if final_token:
            env_updates["BOLTCHAT_SESSION_TOKEN"] = final_token
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        account_path=account_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0
