from __future__ import annotations

import secrets
import sys
from pathlib import Path

from higgsfieldchat.account import HiggsfieldAccount, parse_browser_cookie, save_higgsfield_account
from higgsfieldchat.exceptions import HiggsfieldChatError

_COOKIE_HELP = """
How to copy your Higgsfield browser cookie:

  1. Log in at https://higgsfield.ai
  2. Open DevTools (F12) → Application → Cookies → https://www.higgsfield.ai
  3. Find the "__session" cookie and copy its value
  4. Or run this in the Console tab:
       copy(document.cookie)

  5. Paste the full string here (must include __session).
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _validate_cookie(cookie: str) -> str | None:
    cookie = cookie.strip()
    if not cookie:
        return "Cookie is empty."
    parsed = parse_browser_cookie(cookie)
    if not parsed.get("__session"):
        return "Cookie is missing __session. Copy the full document.cookie string from higgsfield.ai."
    return None


def _read_cookie(*, preset: str | None = None) -> str:
    if preset:
        error = _validate_cookie(preset)
        if error:
            raise HiggsfieldChatError(error, status_code=400)
        return preset.strip()

    _print(_COOKIE_HELP)
    _print()
    while True:
        _print("Paste your Higgsfield cookie (single line), then press Enter:")
        cookie = input("> ").strip()
        error = _validate_cookie(cookie)
        if error is None:
            return cookie
        _print(f"  {error}")
        if not _prompt_yes_no("Try again?", default=True):
            raise HiggsfieldChatError("Setup cancelled.", status_code=1)


def _generate_api_key() -> str:
    return f"sk-higgsfieldchat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m higgsfieldchat setup",
        f"HIGGSFIELDCHAT_API_KEY={values['HIGGSFIELDCHAT_API_KEY']}",
        f"HIGGSFIELDCHAT_HOST={values.get('HIGGSFIELDCHAT_HOST', '127.0.0.1')}",
        f"HIGGSFIELDCHAT_PORT={values.get('HIGGSFIELDCHAT_PORT', '1992')}",
        f"HIGGSFIELDCHAT_ACCOUNT={values.get('HIGGSFIELDCHAT_ACCOUNT', 'higgsfield_account.json')}",
        f"HIGGSFIELDCHAT_BASE_URL={values.get('HIGGSFIELDCHAT_BASE_URL', 'https://higgsfield.ai')}",
        f"HIGGSFIELDCHAT_SC_BASE_URL={values.get('HIGGSFIELDCHAT_SC_BASE_URL', 'https://higgsfield.ai')}",
        f"HIGGSFIELDCHAT_DEFAULT_MODEL={values.get('HIGGSFIELDCHAT_DEFAULT_MODEL', 'supercomputer')}",
    ]
    cookie = values.get("HIGGSFIELD_COOKIE", "").strip()
    if cookie:
        lines.append(f"HIGGSFIELD_COOKIE={cookie}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    account_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    _print()
    _print("Setup complete.")
    _print(f"  Account file : {account_path}")
    if env_written:
        _print(f"  Environment  : {env_path}")
    else:
        _print("  Environment  : (skipped)")
    _print()
    _print("Start the server:")
    _print("  python -m higgsfieldchat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print()
    _print(f"  Base URL: http://{host}:{port}/v1")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    cookie: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    write_cookie_to_env: bool | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = (env_path or Path(".env")).expanduser()
    account_path = (account_path or Path("higgsfield_account.json")).expanduser()
    write_env = True

    _print("HiggsfieldChat setup")
    _print("=====================")
    _print()
    _print("This wizard will:")
    _print("  • validate your Higgsfield browser cookie (__session)")
    _print("  • save higgsfield_account.json")
    _print("  • create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    cookie_value = _read_cookie(preset=cookie)

    parsed = parse_browser_cookie(cookie_value)
    acc = HiggsfieldAccount(
        __session=parsed.get("__session", ""),
        full_cookie=cookie_value.strip().rstrip(";"),
    )
    save_higgsfield_account(acc, account_path)
    _print()
    _print(f"  Account saved to {account_path}")

    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("HIGGSFIELDCHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("HIGGSFIELDCHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("HIGGSFIELDCHAT_PORT") or "1992"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
        include_cookie = write_cookie_to_env if write_cookie_to_env is not None else True
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)
        if write_cookie_to_env is None:
            include_cookie = _prompt_yes_no(
                "Store HIGGSFIELD_COOKIE in .env for auto-refresh on startup?",
                default=True,
            )
        else:
            include_cookie = write_cookie_to_env

    if write_env:
        env_updates = {
            "HIGGSFIELDCHAT_API_KEY": resolved_api_key,
            "HIGGSFIELDCHAT_HOST": resolved_host,
            "HIGGSFIELDCHAT_PORT": resolved_port,
            "HIGGSFIELDCHAT_ACCOUNT": account_path.name,
        }
        if include_cookie:
            env_updates["HIGGSFIELD_COOKIE"] = cookie_value
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        account_path=account_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0