from __future__ import annotations

import sys
from pathlib import Path

from deepseekweb.account import DeepSeekWebAccount, save_deepseek_account
from deepseekweb.exceptions import DeepSeekWebError

_TOKEN_HELP = """
How to get your DeepSeek web token:

  1. Log in at https://chat.deepseek.com
  2. Open DevTools (F12) → Application → Local Storage → https://chat.deepseek.com
  3. Find the "userToken" key and copy its value
  4. (Optional) In Application → Cookies, copy the "ds_session_id" value

Note: this uses your browser session on the free web app (no API balance required).
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _read_token(*, preset: str | None = None) -> str:
    if preset and preset.strip():
        return preset.strip()
    _print(_TOKEN_HELP)
    _print()
    while True:
        _print("Paste your DeepSeek userToken (localStorage), then press Enter:")
        token = input("> ").strip()
        if token:
            return token
        _print("  (required)")


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m deepseekweb setup",
        f"DEEPSEEKWEB_API_KEY={values['DEEPSEEKWEB_API_KEY']}",
        f"DEEPSEEKWEB_HOST={values.get('DEEPSEEKWEB_HOST', '127.0.0.1')}",
        f"DEEPSEEKWEB_PORT={values.get('DEEPSEEKWEB_PORT', '1997')}",
        f"DEEPSEEKWEB_ACCOUNT={values.get('DEEPSEEKWEB_ACCOUNT', 'deepseek_account.json')}",
        f"DEEPSEEKWEB_BASE_URL={values.get('DEEPSEEKWEB_BASE_URL', 'https://chat.deepseek.com/api/v0')}",
        f"DEEPSEEKWEB_DEFAULT_MODEL={values.get('DEEPSEEKWEB_DEFAULT_MODEL', 'deepseek-v4-flash')}",
        "",
        "# userToken: DevTools (F12) → Application → Local Storage → https://chat.deepseek.com → \"userToken\"",
        f"DEEPSEEKWEB_TOKEN={values['DEEPSEEKWEB_TOKEN']}",
        "",
        "# ds_session_id (opsional): DevTools → Application → Cookies → \"ds_session_id\"",
        f"DEEPSEEK_WEB_DS_SESSION_ID={values.get('DEEPSEEK_WEB_DS_SESSION_ID', '').strip()}",
    ]
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    token: str | None = None,
    ds_session_id: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: int | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = env_path or Path("deepseekweb.env")
    account_path = account_path or Path("deepseek_account.json")

    _print("=== DeepSeekWeb (cookie) interactive setup ===")
    if env_path.exists() and not force and not yes:
        answer = input(f"Overwrite existing {env_path}? [y/N]: ").strip().lower()
        if answer not in ("y", "yes"):
            _print("Setup cancelled.")
            return 1

    local_pk = api_key or ("sk-deepseekweb" if yes else _prompt("Local API key", default="sk-deepseekweb"))
    token_val = _read_token(preset=token)
    session_id = ds_session_id if ds_session_id is not None else _prompt("ds_session_id (optional, press Enter to skip)", default="")

    acc = DeepSeekWebAccount(
        user_token=token_val,
        ds_session_id=session_id.strip(),
    )
    save_deepseek_account(acc, account_path)
    _print(f"Saved account to {account_path}")

    updates = {
        "DEEPSEEKWEB_API_KEY": local_pk,
        "DEEPSEEKWEB_HOST": host or "127.0.0.1",
        "DEEPSEEKWEB_PORT": str(port or 1997),
        "DEEPSEEKWEB_ACCOUNT": str(account_path),
        "DEEPSEEKWEB_BASE_URL": "https://chat.deepseek.com/api/v0",
        "DEEPSEEKWEB_DEFAULT_MODEL": "deepseek-v4-flash",
        "DEEPSEEKWEB_TOKEN": token_val,
    }
    if session_id.strip():
        updates["DEEPSEEK_WEB_DS_SESSION_ID"] = session_id.strip()
    _write_env(env_path, updates, overwrite=force or not env_path.exists())
    _print(f"Wrote configuration to {env_path}")
    _print("Start the server with:  python -m deepseekweb serve")
    return 0