from __future__ import annotations

import secrets
import sys
from pathlib import Path

from arenachat.config import Settings, load_settings
from arenachat.exceptions import ArenaChatError

_COOKIE_HELP = """
How to copy your Arena AI browser cookie:

  1. Log in at https://arena.ai
  2. Open DevTools (F12) → Application → Cookies → https://arena.ai
  3. Select all cookie rows, or run this in the Console tab:

       copy(document.cookie)

  4. Paste the full string here.
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _read_cookie(*, preset: str | None = None) -> str:
    if preset:
        return preset.strip()

    _print(_COOKIE_HELP)
    _print()
    while True:
        _print("Paste your Arena AI cookie (single line), then press Enter:")
        cookie = input("> ").strip()
        if cookie:
            return cookie
        _print("  Cookie cannot be empty.")
        if not _prompt_yes_no("Try again?", default=True):
            raise ArenaChatError("Setup cancelled.", status_code=1)


def _generate_api_key() -> str:
    return f"sk-arenachat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m arenachat setup",
        f"ARENACHAT_API_KEY={values['ARENACHAT_API_KEY']}",
        f"ARENACHAT_HOST={values.get('ARENACHAT_HOST', '127.0.0.1')}",
        f"ARENACHAT_PORT={values.get('ARENACHAT_PORT', '1998')}",
        f"ARENACHAT_ACCOUNT={values.get('ARENACHAT_ACCOUNT', 'arena_account.json')}",
        f"ARENACHAT_DEFAULT_MODEL={values.get('ARENACHAT_DEFAULT_MODEL', 'gpt-4o')}",
    ]
    cookie = values.get("ARENACHAT_COOKIE", "").strip()
    if cookie:
        lines.append(f"ARENACHAT_COOKIE={cookie}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    _print()
    _print("Setup complete.")
    if env_written:
        _print(f"  Environment  : {env_path}")
    else:
        _print("  Environment  : (skipped)")
    _print()
    _print("Start the server:")
    _print("  python -m arenachat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print()
    _print(f"  Base URL: http://{host}:{port}/v1")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    cookie: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = (env_path or Path(".env")).expanduser()
    write_env = True

    _print("ArenaChat setup")
    _print("===============")
    _print()
    _print("This wizard will:")
    _print("  • validate your Arena AI browser cookie")
    _print("  • create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    cookie_value = _read_cookie(preset=cookie)

    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("ARENACHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("ARENACHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("ARENACHAT_PORT") or "1998"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)

    if write_env:
        env_updates = {
            "ARENACHAT_API_KEY": resolved_api_key,
            "ARENACHAT_HOST": resolved_host,
            "ARENACHAT_PORT": resolved_port,
            "ARENACHAT_COOKIE": cookie_value,
        }
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0
