from __future__ import annotations

import secrets
import sys
from pathlib import Path

from pokeechat.exceptions import PokeeChatError

_API_KEY_HELP = """
How to get your Pokee API key:

  1. Log in at https://console.pokee.ai
  2. Open the API Keys page (https://console.pokee.ai/keys)
  3. Create a key (it is shown only once) and copy it
  4. Paste the value here (starts with "pk-")
""".strip()

DEFAULT_BASE_URL = "https://api.pokee.ai/v1"


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _validate_pokee_key(key: str) -> str | None:
    key = key.strip()
    if not key:
        return "API key is empty."
    return None


def _read_pokee_key(*, preset: str | None = None) -> str:
    if preset:
        error = _validate_pokee_key(preset)
        if error:
            raise PokeeChatError(error, status_code=400)
        return preset.strip()
    _print(_API_KEY_HELP)
    _print()
    while True:
        _print("Paste your Pokee API key (starts with pk-), then press Enter:")
        key = input("> ").strip()
        error = _validate_pokee_key(key)
        if error is None:
            return key
        _print(f"  {error}")


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m pokeechat setup",
        f"POKEECHAT_API_KEY={values['POKEECHAT_API_KEY']}",
        f"POKEECHAT_HOST={values.get('POKEECHAT_HOST', '127.0.0.1')}",
        f"POKEECHAT_PORT={values.get('POKEECHAT_PORT', '1993')}",
        f"POKEECHAT_BASE_URL={values.get('POKEECHAT_BASE_URL', 'https://api.pokee.ai/v1')}",
        f"POKEECHAT_DEFAULT_MODEL={values.get('POKEECHAT_DEFAULT_MODEL', 'pokee-isaac')}",
        f"POKEE_API_KEY={values['POKEE_API_KEY']}",
    ]
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def run_interactive_setup(
    *,
    env_path: Path | None = None,
    api_key: str | None = None,
    pokee_api_key: str | None = None,
    host: str | None = None,
    port: int | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = env_path or Path(".env")

    _print("=== PokeeChat interactive setup ===")
    if env_path.exists() and not force and not yes:
        answer = input(f"Overwrite existing {env_path}? [y/N]: ").strip().lower()
        if answer not in ("y", "yes"):
            _print("Setup cancelled.")
            return 1

    local_pk = api_key or ("sk-pokeechat" if yes else _prompt("Local API key", default="sk-pokeechat"))
    pokee_key = _read_pokee_key(preset=pokee_api_key)

    updates = {
        "POKEECHAT_API_KEY": local_pk,
        "POKEECHAT_HOST": host or "127.0.0.1",
        "POKEECHAT_PORT": str(port or 1993),
        "POKEECHAT_BASE_URL": "https://api.pokee.ai/v1",
        "POKEECHAT_DEFAULT_MODEL": "pokee-isaac",
        "POKEE_API_KEY": pokee_key,
    }
    _write_env(env_path, updates, overwrite=force or not env_path.exists())
    _print(f"Wrote configuration to {env_path}")
    _print("Start the server with:  python -m pokeechat serve")
    return 0