from __future__ import annotations

import secrets
import sys
from pathlib import Path

from kimichat.account import extract_refresh_token
from kimichat.bootstrap import bootstrap_from_token
from kimichat.exceptions import KimiChatError

_TOKEN_HELP = """
How to get your Kimi refresh_token:

  1. Open https://www.kimi.com in your browser and log in.
  2. Open DevTools (F12) -> Application -> Local Storage -> https://www.kimi.com
  3. Copy the value of the key "refresh_token" (a long JWT starting with "eyJ...").
  4. Paste it below.

Alternatively, paste the full document.cookie and the wizard will try to
extract refresh_token from it.
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _prompt_yes_no(label: str, *, default: bool = True) -> bool:
    hint = "Y/n" if default else "y/N"
    while True:
        value = input(f"{label} [{hint}]: ").strip().lower()
        if not value:
            return default
        if value in ("y", "yes"):
            return True
        if value in ("n", "no"):
            return False
        _print("  Please answer y or n.")


def _generate_api_key() -> str:
    return f"sk-kimichat-{secrets.token_urlsafe(18)}"


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m kimichat setup",
        f"KIMICHAT_API_KEY={values['KIMICHAT_API_KEY']}",
        f"KIMICHAT_HOST={values.get('KIMICHAT_HOST', '127.0.0.1')}",
        f"KIMICHAT_PORT={values.get('KIMICHAT_PORT', '1997')}",
        f"KIMICHAT_ACCOUNT={values.get('KIMICHAT_ACCOUNT', 'kimi_account.json')}",
        f"KIMICHAT_DEFAULT_MODEL={values.get('KIMICHAT_DEFAULT_MODEL', 'kimi')}",
    ]
    refresh = values.get("KIMICHAT_REFRESH_TOKEN", "").strip()
    if refresh:
        lines.append(f"KIMICHAT_REFRESH_TOKEN={refresh}")
    cookies = values.get("KIMICHAT_COOKIES", "").strip()
    if cookies:
        lines.append(f"KIMICHAT_COOKIES={cookies}")
    device = values.get("KIMICHAT_DEVICE_ID", "").strip()
    if device:
        lines.append(f"KIMICHAT_DEVICE_ID={device}")
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def _print_success(
    *,
    env_written: bool,
    env_path: Path,
    account_path: Path,
    host: str,
    port: str,
    api_key: str,
) -> None:
    _print()
    _print("Setup complete.")
    _print(f"  Account file : {account_path}")
    _print(f"  Environment  : {env_path if env_written else '(skipped)'}")
    _print()
    _print("Start the server:")
    _print("  python -m kimichat serve")
    _print()
    _print("Quick test:")
    _print(f"  curl http://{host}:{port}/healthz")
    _print()
    _print("Use this API key in your OpenAI-compatible client:")
    _print(f"  {api_key}")
    _print(f"  Base URL: http://{host}:{port}/v1")


async def run_interactive_setup(
    *,
    env_path: Path | None = None,
    account_path: Path | None = None,
    token: str | None = None,
    api_key: str | None = None,
    host: str | None = None,
    port: str | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = (env_path or Path(".env")).expanduser()
    account_path = (account_path or Path("kimi_account.json")).expanduser()
    write_env = True

    _print("KimiChat setup")
    _print("==============")
    _print()
    _print("This wizard will:")
    _print("  - validate your Kimi refresh_token from kimi.com")
    _print("  - save kimi_account.json")
    _print("  - create or update .env for the local API server")
    _print()

    if env_path.exists() and not force and not yes:
        if not _prompt_yes_no(f"{env_path} already exists. Update it?", default=False):
            write_env = False

    if token:
        raw = token
    else:
        _print(_TOKEN_HELP)
        _print()
        _print("Paste your Kimi refresh_token (or cookie), then press Enter:")
        raw = input("> ").strip()

    final_token, final_cookies = extract_refresh_token(raw)
    if not final_token:
        _print("  Error: could not find a refresh_token in the input.", file=sys.stderr)
        return 1

    _print()
    _print("Validating refresh_token with Kimi...")
    try:
        account = await bootstrap_from_token(
            final_token,
            cookies=final_cookies,
            account_path=str(account_path),
        )
    except KimiChatError as exc:
        _print(f"  Error: {exc}", file=sys.stderr)
        return 1

    _print(f"  User: {account.user_name or account.user_id or '(unknown)'}")

    existing_env = _parse_env_file(env_path) if env_path.exists() else {}
    default_api_key = api_key or existing_env.get("KIMICHAT_API_KEY") or _generate_api_key()
    default_host = host or existing_env.get("KIMICHAT_HOST") or "127.0.0.1"
    default_port = port or existing_env.get("KIMICHAT_PORT") or "1997"

    if yes:
        resolved_api_key = default_api_key
        resolved_host = default_host
        resolved_port = default_port
    else:
        _print()
        _print("Server settings (Enter keeps the default):")
        resolved_api_key = _prompt("API key clients must send", default=default_api_key)
        resolved_host = _prompt("Bind host", default=default_host)
        resolved_port = _prompt("Port", default=default_port)

    if write_env:
        env_updates = {
            "KIMICHAT_API_KEY": resolved_api_key,
            "KIMICHAT_HOST": resolved_host,
            "KIMICHAT_PORT": resolved_port,
            "KIMICHAT_ACCOUNT": account_path.name,
            "KIMICHAT_REFRESH_TOKEN": account.refresh_token or final_token,
        }
        if final_cookies:
            env_updates["KIMICHAT_COOKIES"] = final_cookies
        if account.device_id:
            env_updates["KIMICHAT_DEVICE_ID"] = account.device_id
        overwrite = force or yes or not env_path.exists()
        _write_env(env_path, env_updates, overwrite=overwrite)
        _print(f"  Wrote {env_path}")

    _print_success(
        env_written=write_env,
        env_path=env_path,
        account_path=account_path,
        host=resolved_host,
        port=resolved_port,
        api_key=resolved_api_key,
    )
    return 0
