from __future__ import annotations

import sys
from pathlib import Path

from deepseekchat.exceptions import DeepSeekChatError

_API_KEY_HELP = """
How to get your DeepSeek API key:

  1. Sign up at https://platform.deepseek.com
  2. New accounts get 5M free tokens (valid 30 days)
  3. Open API Keys and create a key (starts with "sk-")
  4. Paste the value here
""".strip()


def _print(msg: str = "", *, file=None) -> None:
    print(msg, file=file or sys.stdout)


def _prompt(label: str, *, default: str | None = None) -> str:
    suffix = f" [{default}]" if default else ""
    while True:
        value = input(f"{label}{suffix}: ").strip()
        if value:
            return value
        if default is not None:
            return default
        _print("  (required)")


def _read_deepseek_key(*, preset: str | None = None) -> str:
    if preset and preset.strip():
        return preset.strip()
    _print(_API_KEY_HELP)
    _print()
    while True:
        _print("Paste your DeepSeek API key (starts with sk-), then press Enter:")
        key = input("> ").strip()
        if key:
            return key
        _print("  (required)")


def _parse_env_file(path: Path) -> dict[str, str]:
    if not path.exists():
        return {}
    values: dict[str, str] = {}
    for line in path.read_text(encoding="utf-8").splitlines():
        stripped = line.strip()
        if not stripped or stripped.startswith("#") or "=" not in stripped:
            continue
        key, _, value = stripped.partition("=")
        values[key.strip()] = value.strip()
    return values


def _render_env(values: dict[str, str]) -> str:
    lines = [
        "# Generated by: python -m deepseekchat setup",
        f"DEEPSEEKCHAT_API_KEY={values['DEEPSEEKCHAT_API_KEY']}",
        f"DEEPSEEKCHAT_HOST={values.get('DEEPSEEKCHAT_HOST', '127.0.0.1')}",
        f"DEEPSEEKCHAT_PORT={values.get('DEEPSEEKCHAT_PORT', '1996')}",
        f"DEEPSEEKCHAT_BASE_URL={values.get('DEEPSEEKCHAT_BASE_URL', 'https://api.deepseek.com')}",
        f"DEEPSEEKCHAT_DEFAULT_MODEL={values.get('DEEPSEEKCHAT_DEFAULT_MODEL', 'deepseek-v4-flash')}",
        f"DEEPSEEK_API_KEY={values['DEEPSEEK_API_KEY']}",
    ]
    lines.append("")
    return "\n".join(lines)


def _write_env(path: Path, updates: dict[str, str], *, overwrite: bool) -> None:
    merged = _parse_env_file(path) if path.exists() and not overwrite else {}
    merged.update(updates)
    path.write_text(_render_env(merged), encoding="utf-8")


def run_interactive_setup(
    *,
    env_path: Path | None = None,
    api_key: str | None = None,
    deepseek_api_key: str | None = None,
    host: str | None = None,
    port: int | None = None,
    force: bool = False,
    yes: bool = False,
) -> int:
    env_path = env_path or Path("deepseek.env")

    _print("=== DeepSeekChat interactive setup ===")
    if env_path.exists() and not force and not yes:
        answer = input(f"Overwrite existing {env_path}? [y/N]: ").strip().lower()
        if answer not in ("y", "yes"):
            _print("Setup cancelled.")
            return 1

    local_pk = api_key or ("sk-deepseekchat" if yes else _prompt("Local API key", default="sk-deepseekchat"))
    ds_key = _read_deepseek_key(preset=deepseek_api_key)

    updates = {
        "DEEPSEEKCHAT_API_KEY": local_pk,
        "DEEPSEEKCHAT_HOST": host or "127.0.0.1",
        "DEEPSEEKCHAT_PORT": str(port or 1996),
        "DEEPSEEKCHAT_BASE_URL": "https://api.deepseek.com",
        "DEEPSEEKCHAT_DEFAULT_MODEL": "deepseek-v4-flash",
        "DEEPSEEK_API_KEY": ds_key,
    }
    _write_env(env_path, updates, overwrite=force or not env_path.exists())
    _print(f"Wrote configuration to {env_path}")
    _print("Start the server with:  python -m deepseekchat serve")
    return 0